db: jdbc:mysql://blackboard-db-prod01.cd0fd80v826l.us-west-2.rds.amazonaws.com:3306/blackboard_prod01?user=cmlicata&password=timmykim123&useUnicode=true&characterEncoding=UTF-8
driver: com.mysql.jdbc.Driver